spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/cafe}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:12345678}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

logging:
  level:
    org.hibernate.SQL: debug

ranking:
  cache:
    ttl: ${RANKING_CACHE_TTL:5m}
