spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3307/coffee_order}
    username: ${DB_USERNAME:coffee}
    password: ${DB_PASSWORD:coffee}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: com.jihyeon.coffeeorder.order.event

kafka:
  topic:
    order-completed: ${KAFKA_ORDER_COMPLETED_TOPIC:coffee.order.completed.v1}
  consumer:
    order-completed-group: ${KAFKA_ORDER_COMPLETED_GROUP:ranking-order-completed-v1}

logging:
  level:
    org.hibernate.SQL: debug

ranking:
  cache:
    ttl: ${RANKING_CACHE_TTL:5m}
